#'@name GroundSurfaceCreate
#'@title write missing extention into catalog.exe generated .csv 
#'
#'@description
#' writes missing extention into catalog.exe generated .csv by substringing .las filename
#'
#'@author Chris Reudenbach,Jannis Gottwald
#'
#'@param catalogTable  default is \code{NULL} .csv generated by catalog.exe
#'
#'@examples
#'\dontrun{
#' # repair loaded .csv and store in new object
#' oldTable<-read.csv(paste0(filepath, lasfilename,".csv))
#' newTable<-missingExtents(oldTable)
#'}
#'


missingExtents<-function(catalogTable){
  
  for (i in 3:nrow(catalogTable)){
    
    findrows <- which(catalogTable$MinX ==0|catalogTable$MinY==0|
                        catalogTable$MaxX==0|catalogTable$MaxY==0)
    
    for (j in findrows){
      coor<-substr(catalogTable[j,1],nchar(as.character(catalogTable[j,1]))-10, nchar(as.character(catalogTable[j,1])))
      
      xmin<-paste0(substr(coor, 1,3), "000")
      
      ymin<-paste0(substr(coor, 4,7), "000")
      
      catalogTable[j,]$MinX=as.numeric(xmin)
      
      catalogTable[j,]$MinY=as.numeric(ymin)
    }}
  catalogTable$MaxX<-round(catalogTable$MaxX,0)
  
  catalogTable$MaxY<-round(catalogTable$MaxY,0)
  
  return(catalogTable)
  
}

#'@name densityMetrics
#'@title Create height specific proportions of points and canopy height model as dtm* object from a LiDAR generated point cloud 
#'
#'@description
#' Create height specific proportions of points and canopy height model as dtm* object from a LiDAR generated point cloud 
#'
#'@author Chris Reudenbach,Jannis Gottwald
#'
#'@param lasFiles  default is \code{NULL} list of the las file(s)
#'@param heightClassList default is \code{list(c(0,2,5,10,30))}  
#'@param res resolution for raster operations 
#'@examples
#'\dontrun{
#' # create proportions, all returns, canopy height model in dtm
#' densityMetrics(lasFiles = lasfiles, heightClassList =heights, res = 10 )
#'}
#'
#'




densityMetrics<-function(lasFiles, heightClassList, res){
  
  slices<-paste(unlist(heightClassList), collapse = ",")
  for (i in lasFiles){
    command<-Fusion
    command<-paste0(command,"densitymetrics.exe")
    command<-paste0(command, " ", "/slices:")
    command<-paste0(command,slices)
    command<-paste0(command, " ",gi_run,"surf_",i,".dtm" )
    command<-paste0(command," ", res, " ", 0)
    command<-paste0(command," ", gi_run,i,"SliceProportion_", ".dtm"   )
    command<-paste0(command," ", gi_input, i )
    system(command)
    
    
  }}



#'@name GroundSurfaceCreate
#'@title Create a DEM raster* object from a LiDAR generated point cloud 
#'
#'@description
#' Create a DEM raster* object from a LiDAR generated point cloud based on regular las format files
#'
#'@author Chris Reudenbach,Jannis Gottwald
#'
#'@param lasFiles  default is \code{NULL} list of the las file(s)
#'@param res resolution for raster operations 
#'@examples
#'\dontrun{
#' # create a DSM based on a uav point cloud 
#' GroundSurfaceCreate(lasFiles = lasfiles, res=10)
#'}
#'

GroundSurfaceCreate<-function(lasFiles, res ){
  
  
  paramList <- c(paste(as.character(res),"M M 1 32 0 0 "))

  
  for (i in 1:length(lasFiles)) {
    ### --> retrieve infomation from las file
 
    
    # calculate extents etc...
    
    #--> Fusion catalog 
    command<-Fusion
    command<-paste0(command, "catalog.exe")
    command<-paste0(command," ", gi_input, basename(lasFiles[i]) )
    command<-paste0(command," ", gi_run, i,".html"   )
    system(command)
    
    #--> extract extent info 
    info <- read.csv(paste0(gi_run,i,".csv"))
    #fix extent
    info2<-missingExtents(info)
    #TODO  fix error in las files if (as.numeric(info[[2]][3])) fixLas()
    #--> define extent for further calculation
    extent<-paste(as.numeric(info2$MinX),as.numeric(info2$MinY),as.numeric(info2$MaxX),as.numeric(info2$MaxY))
    ext<-c(as.numeric(info2$MinX),as.numeric(info2$MinY),as.numeric(info2$MaxX),as.numeric(info2$MaxY))
    
  
    #--> Create a .las with groundpoints only 
      command<-Fusion
      command<-paste0(command, "clipdata.exe")
      command<-paste0(command," ","/class:2 ")
      command<-paste0(command," ", gi_input, basename(lasFiles[i])   )
      command<-paste0(command," ", gi_run,"ground_",basename(lasFiles[i])   )
      command<-paste0(command," ", extent)
    system(command)  
    
    #--> Create the required PLANS DTM format 
      command<-Fusion
      command<-paste0(command, "gridsurfacecreate.exe")
      command<-paste0(command," ", gi_run,"surf_",basename(lasFiles[i]),".dtm")
      command<-paste0(command," ", paramList  )
      command<-paste0(command," ", gi_run,"ground_",basename(lasFiles[i])   )
    system(command) 
}}
    
  

    
#'@name readAscGridMetrics
#'@title lists only the desired densityMetrics asc from outputfolder
#'
#'@description
#'lists only the desired densityMetrics asc from outputfolder
#'
#'@author Chris Reudenbach,Jannis Gottwald
#'
#'@param lasFiles  default is \code{NULL} list of the las file(s)
#'@param heightClasses default is \code{list(c(0,2,5,10,30))}  
#'@examples
#'\dontrun{
#'  GridList<-readAscGridMetrics(lasFiles = lasfiles, heightClasses = heights)
#' 
#'}
#'
#'




readAscGridMetrics<-function(lasFiles, heightClasses){
  AscGridMetrics<-list()
  
  AscGridMetrics<-vector("list", length(lasFiles))
  
  for(i in 1:length(lasFiles)){
    
    maxHeights<-paste0(gi_run,lasFiles[i],"SliceProportion_","_all_returns_max_height.dtm",".asc")
    totalReturns<-paste0(gi_run,lasFiles[i],"SliceProportion_"," _all_returns_total_returns.dtm",".asc")
    AscGridMetrics[[i]][length(heightClasses[[1]])+1]<-maxHeights
    AscGridMetrics[[i]][length(heightClasses[[1]])+2]<-maxHeights
    
    for (j in 1:length(heightClasses[[1]])){
      prop<-paste0(gi_run,lasFiles[i],"SliceProportion_","_all_returns_slice_",j, ".dtm",".asc")
      AscGridMetrics[[i]][j]<-prop}}
  return(AscGridMetrics)}

#'@name densityMetrics2asci
#'@title list all densityMetricsProducts and convert them into GIS-readable asc
#'
#'@description
#' list all densityMetricsProducts and convert them into GIS-readable asc
#'
#'@author Chris Reudenbach,Jannis Gottwald
#'
#'
#'@param lasFiles  default is \code{NULL} list of the las file(s)
#'@param heightClasses default is \code{list(c(0,2,5,10,30))}  
#'@examples
#'\dontrun{
#' 
#'densityMetrics2asci(lasFiles = lasfiles, heightClasses = heights)
#'}
#'
#'
#'
#'
densityMetrics2asci<-function(lasFiles, heightClasses){
  
  for(i in 1:length(lasFiles)){
    #put maxHeights
    command<-Fusion
    command<-paste0(command, "dtm2ascii.exe")
    maxHeights<-paste0(gi_run,lasFiles[i],"SliceProportion_","_all_returns_max_height.dtm")
    command<-paste0(command, " ",maxHeights )
    command<-paste0(command, " ",gi_run, maxHeights, ".asc" )
    system(command)
    #and total Returns 
    command<-Fusion
    command<-paste0(command, "dtm2ascii.exe")
    totalReturns<-paste0(gi_run,lasFiles[i],"SliceProportion_","_all_returns_total_returns.dtm")
    command<-paste0(command, " ",totalReturns )
    command<-paste0(command, " ",totalReturns, ".asc" )
    system(command)
    
    for (j in 1:length(heightClasses[[1]])){
      #put pi (proportion in the ith layer) 
      prop<-paste0(gi_run,lasFiles[i],"SliceProportion_","_all_returns_slice_",j, ".dtm")
      #in the slots before
        command<-Fusion
        command<-paste0(command, "dtm2ascii.exe")
        command<-paste0(command, " ",prop )
        command<-paste0(command, " ", prop, ".asc" )
        system(command)
      }}}


  







